//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=WeightingSystem;Integrated Security=True" +
            "")]
        public string SBMS_SQL_SBMSEE {
            get {
                return ((string)(this["SBMS_SQL_SBMSEE"]));
            }
            set {
                this["SBMS_SQL_SBMSEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=wboee.world;User ID=SBMSee;Password=SBMS#0324;Unicode=True")]
        public string CS_Oracle_SBMSEE {
            get {
                return ((string)(this["CS_Oracle_SBMSEE"]));
            }
            set {
                this["CS_Oracle_SBMSEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=wboee.world;User ID=ubct;Password=ubct01;Unicode=True")]
        public string CS_Oracle_UBCT {
            get {
                return ((string)(this["CS_Oracle_UBCT"]));
            }
            set {
                this["CS_Oracle_UBCT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=oeetest;User ID=shangrila;Password=paradise;Unicode=True")]
        public string SBMS_Oracle_OEETEST {
            get {
                return ((string)(this["SBMS_Oracle_OEETEST"]));
            }
            set {
                this["SBMS_Oracle_OEETEST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.Oledb.4.0;Data Source=c:\\App1\\你的数据库名.mdb;")]
        public string SBMS_OleDb_Shangrila {
            get {
                return ((string)(this["SBMS_OleDb_Shangrila"]));
            }
            set {
                this["SBMS_OleDb_Shangrila"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=oeetest;User ID=shangrila;Password=paradise;Unicode=True")]
        public string CS_Oracle_SHANGRILA {
            get {
                return ((string)(this["CS_Oracle_SHANGRILA"]));
            }
            set {
                this["CS_Oracle_SHANGRILA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CARDTEST-PC1\\SQLEXPRESS;Initial Catalog=WeightingSystem;User Id=sa;Pa" +
            "ssword=SBMS12345 ;Integrated Security=True")]
        public string SBMS_SQL_SBMSEE2 {
            get {
                return ((string)(this["SBMS_SQL_SBMSEE2"]));
            }
            set {
                this["SBMS_SQL_SBMSEE2"] = value;
            }
        }
    }
}
